# Generated by Django 4.0.6 on 2022-08-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='Symbol',
            new_name='symbol',
        ),
    ]
